### ISSUE TITLE
[Crash]: After init with Server Translation API

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/universalenchants#17]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.3

### Notes (Required)

1. Install Universal Enchants, its dependencies and [Server Translation API](https://www.curseforge.com/minecraft/mc-mods/server-translation-api)
2. Launch the game, it will crash after Mojang loading screen

The issue is present on Fabric and Quilt. Let me know if this needs to be reported to Server Translation API instead.

### Crash Report (Required)

https://gist.github.com/SplendidAlakey/bffd9e87c67b2f43e88de984d09376a8

### latest.log (Optional)

https://gist.github.com/SplendidAlakey/bffd9e87c67b2f43e88de984d09376a8

**Comment by Fuzss** [comment]
They loop indefinitely until memory runs out. 

You can probably disable Roman numerals in the client config until there‘s a fix.

**Comment by Footage2-Amply-Pounce** [comment]
Yep, setting `fix_roman_numerals` to `NONE` works for the time being. But just an FYI, setting it to `ARABIC` still causes a crash.

Thanks for looking into it!

**Comment by FeyXieXzf** [comment]
> Yep, setting fix_roman_numerals to NONE works for the time being. But just an FYI, setting it to ARABIC still causes a crash.
> Thanks for looking into it!

I have met the save problem and can confirm that this fix works for me.

**Comment by Patbox** [comment]
One solution to this issue would be mixin into vanilla language object instead of wrapping it (at least on fabric side). 

Alternative is autodisabling that system when STAPI is loaded, but thats bad solution

**Comment by TheSpiderDungeon** [comment]
Can confirm crash is still happening Nov. 29; workaround posted here works.

**Comment by Fuzss** [comment]
I've made it now so that the roman numerals fix is basically disabled when Server Translation API is installed (it only applies when the language instance is the vanilla language class and won't respond to a wrapper like the on STAPI is using).

This is not a great solution, but I think that's the best I can do for now.

I feel like using mixins here is simply is not necessary, both on my and STAPI's end. A simple reload listener should be enough for both, and would make everything compatible out of the box. I'll leave a slightly more detailed suggestion on how to implement this on STAPI's repo.
