### ISSUE TITLE
Compatibility with Modded weapons?

### ISSUE THREAD

**Issue by 4AC11** [Fuzss/universalenchants#7]
I've been using this mod with Dragonloot installed, and although I am able to apply enchantments to the items, some enchantments (ones for Dragon Bow and Dragon Crossbow specifically) don't actually work, including Power and Punch. This leaves the vanilla crossbow being leagues stronger than its Dragon counterpart simply because it is able to use Power and the Dragon variant is not. :(

Other enchantment combos, such as Impaling on swords or Sharpness on Tridents, seems to work fine with all modded swords, so it seems like this should be possible to fix (Though I don't know how difficult it would be)

**Comment by Fuzss** [comment]
Enchantments (especially the ones for bow and crossbow) are implemented using a bunch of hardcoded cases. Allowing vanilla's items to support additional enchantments already is a lot of work, so I won't be targeting individual mods.

Since those enchantments don't work on the bow/crossbow, I'd recommend blacklisting those items in the config, so that you don't get the enchantments on them in survival.

If you're hoping to get support for these enchantments you're better off asking the mod author of DragonLoot to handle when enchantments such as power and punch are present.
